### ISSUE TITLE
Asking the original paper

### ISSUE THREAD

**Issue by TGS123** [dhanwin247/Parallel-graph-coloring#1]
Sorry to be a bother .I read the code seriously and I am very interested
 in it.
      Presently, I am researching some related issues, and I wonder if you can
 send me your original paper or document which would give me a great of help
 in comprehending your code and making some comparisons with mine. I
 will be appreciated for your reply as soon as possible, thank you very much!

       Best wishes.
       Yours respectfully.

**Comment by dhanwin247** [comment]
http://www.new-npac.org/users/fox/pdftotal/sccs-0666.pdf

**Comment by TGS123** [comment]
Thank you for your reply. I will read it seriously.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dhanwin247/Parallel-graph-coloring"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月5日(星期二) 晚上6:41
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dhanwin247/Parallel-graph-coloring] Asking the original paper (Issue #1)





 
http://www.new-npac.org/users/fox/pdftotal/sccs-0666.pdf
